apiVersion: redhatcop.redhat.io/v1alpha1
kind: Patch
metadata:
  name: patch-router-external-apps-service
spec:
  serviceAccountRef:
    name: patcher
  patches:
    patch-router-external-apps-service:
      targetObjectRef:
        apiVersion: v1
        kind: Service
        name: router-external-apps
      patchType: application/strategic-merge-patch+json
      patchTemplate: |
        apiVersion: v1
        kind: Service
        metadata:
          annotations:
            metallb.universe.tf/address-pool: public
            metallb.universe.tf/loadBalancerIPs: 100.64.0.100
          name: router-external-apps
          namespace: openshift-ingress
        spec:
          loadBalancerIP: 100.64.0.100

          # The Ingress operator creates the Service with externalTrafficPolicy [1] set
          # to "Local", but that appears to cause problems (at least on SNO).
          #
          # [1]: https://kubernetes.io/docs/tasks/access-application-cluster/create-external-load-balancer/#preserving-the-client-source-ip
          externalTrafficPolicy: Cluster
          internalTrafficPolicy: Cluster
