apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:
  external-ingress-demo/deployment-stage: stage2
  external-ingress-demo/kustomized: "true"
  cluster-guard/enabled: "true"
resources:
- nmstate
- metallb
