apiVersion: machineconfiguration.openshift.io/v1
kind: MachineConfig
metadata:
  labels:
    machineconfiguration.openshift.io/role: "master"
  name: disable-net-prio
spec:
  config:
    ignition:
      version: 3.2.0
  kernelArguments:
    - cgroup_no_v1=net_prio,net_cl
