apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: patcher-openshift-ingress
rules:
- apiGroups:
  - ""
  resources:
  - services
  verbs:
  - get
  - list
  - watch
  - patch
  - update
