apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: patcher-openshift-ingress
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: patcher-openshift-ingress
subjects:
- kind: ServiceAccount
  name: patcher
  namespace: openshift-ingress
