apiVersion: machineconfiguration.openshift.io/v1
kind: MachineConfig
metadata:
  name: ssh
spec:
  config:
    ignition:
      version: 3.2.0
    passwd:
      users:
        - name: core
          sshAuthorizedKeys:
            - ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAACAQDHU+dRblINH9VOKWKluyyE1xz0GG6YMIiTCgUlDrEzvybC0Y0luIj87rQFHmihYFrmYdrCe2v2dFo1LggJEMPh3jfrXzJVl7KjbTOdsUSVwWCHD07uAiyNmH7aNGFuS4B6oiQj5NSTzl5C0Mvt/JIZmkky2305tZoF40bGlHP/U3tXoU+QPRqV44HR0AdkMArHADQoR/cpEQJantNuQsV2BouzfOJ8GcFLDU2ZPESgubrd4CxQ7p2+uujl0WsTsz0Ip3FkJINBHBnOGM9NteHVsiGJgmg3oeOhcH31bjYOToRNKvjAiepAsQMjhfm3GE850DcFJO6kEGD8umbhRiXZIfGJkqw1HWzcaN09q9cOWczMUytGBy6BGc7eNdf03F9FHLOO8c5gcA6Sd7rJFZD6LbRv+O8mtbLpL9Bi41I/5vNgNo0HI0Z2w56r9F8rRQ+jy4HR29hvV5yR7LZHC2kJ3TZiZBeqy5UG6SlQI4fOq1JHQ9/IzT4wV+sxQz38k3Yir6RE/Yg9N8wTMxpYG5/LsXa/eGRThCRbbaY5IgSK4NAWDDhMEt9TqTwrNSzEMi6Xv5DLROtyctUNN5fcN2M+evcJ4GqUgaw87e6Jk89cyQj/f3XLRjO2Yxudl5uLDd4f5aOnMJxsr8+3j5xMe8BNM9VkZqhPM/FEhi40xAl9lQ==
            - ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQC8lmJWUvyvYWhNC+Q268tZlxKNxlYFSRze7nXI+WSdLvfk8FzyK3sqZ8kGqpGGDodRvYjMoDyoz6jpA7Fg8DsqL6X+aY3G42us6KygXHQ2xsaOVhbSvW22FX02I1c063E30ui+5L4BI3UvtgJih72SDoG7SpM1sdNSd2Dmr0gsdC6rHPOcg5TlTcA7lbTb48IBVn+3hDXCgvgsWv1Hk4c0wWKbRAaN3gQUW9rR/BshMmjpr4G/4N13+hONZUS6fi3VB1HWtd5jSD1ZLBIPghViij528FryD17W9b0nMS7IBrl3WMLwp3IEIz/uzKfJgY3JQZSsV0/7eBNkotS9I2rz
