apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:
  external-ingress-demo/deployment-stage: stage1
  external-ingress-demo/kustomized: "true"
commonAnnotations:
  cluster-guard/target-cluster: "cluster0.openshift.virt"
resources:
- machineconfigs
- subscriptions
- custom-logo
