apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - console.yaml

generatorOptions:
  disableNameSuffixHash: true

configMapGenerator:
- files:
  - splat.png
  name: oddbit-logo
  namespace: openshift-config
