apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: patcher-openshift-ingress-operator
rules:
- apiGroups:
  - "operator.openshift.io"
  resources:
  - ingresscontrollers
  verbs:
  - get
  - list
  - watch
  - patch
  - update
