apiVersion: v1
kind: Service
metadata:
  annotations:
    metallb.universe.tf/address-pool: public
  name: router-external-apps
  namespace: openshift-ingress
spec:
  loadBalancerIP: 100.64.0.100

  # The Ingress operator creates the Service with externalTrafficPolicy [1] set
  # to "Local", but that appears to cause problems (at least on SNO).
  #
  # [1]: https://kubernetes.io/docs/tasks/access-application-cluster/create-external-load-balancer/#preserving-the-client-source-ip
  externalTrafficPolicy: Cluster
  internalTrafficPolicy: Cluster
